#!/bin/sh

export PUREGEV_ROOT=/opt/pleora/ebus_sdk/Ubuntu-12.04-x86_64
export GENICAM_ROOT=$PUREGEV_ROOT/lib/genicam
export GENICAM_ROOT_V2_4=$GENICAM_ROOT
export GENICAM_LOG_CONFIG=$GENICAM_ROOT/log/config/DefaultLogging.properties
export GENICAM_LOG_CONFIG_V2_4=$GENICAM_LOG_CONFIG
if [ "$HOME" = "/" ]; then
  export GENICAM_CACHE_V2_4=/.config/Pleora/genicam_cache_v2_4
else
  export GENICAM_CACHE_V2_4=$HOME/.config/Pleora/genicam_cache_v2_4
fi
export GENICAM_CACHE=$GENICAM_CACHE_V2_4
export GENICAM_LIB_DIR=$GENICAM_ROOT/bin/Linux64_x64
mkdir -p $GENICAM_CACHE

if ! echo ${LD_LIBRARY_PATH} | grep -q ${PUREGEV_ROOT}/lib; then
  if [ "$LD_LIBRARY_PATH" = "" ]; then
    LD_LIBRARY_PATH=${PUREGEV_ROOT}/lib
  else
    LD_LIBRARY_PATH=${PUREGEV_ROOT}/lib:${LD_LIBRARY_PATH}
  fi
fi

if ! echo ${LD_LIBRARY_PATH} | grep -q ${GENICAM_LIB_DIR}; then
  LD_LIBRARY_PATH=${GENICAM_LIB_DIR}:${LD_LIBRARY_PATH}
fi

export LD_LIBRARY_PATH

if ! echo ${PATH} | grep -q ${PUREGEV_ROOT}/bin; then
  PATH=${PUREGEV_ROOT}/bin:${PATH}
fi

export PATH

unset GENICAM_LIB_DIR

